### ISSUE TITLE
Weird face behavior

### ISSUE THREAD

**Issue by wandersoncferreira** [kostafey/organic-green-theme#5]
Hello @kostafey how are you?

I just noticed something while using Emacs today. While I am typing the color of some portions of the buffer gets a little different, I took these two screenshots to contrast before/after saving the buffer.

Before:

![weird_color_organic](https://user-images.githubusercontent.com/17708295/86065512-2e91b700-ba46-11ea-8a0b-20af3e16f250.png)

After:

![correct_organic](https://user-images.githubusercontent.com/17708295/86065530-37828880-ba46-11ea-902a-bd3e6274b18b.png)

I dont know exactly how to explain, but I was expecting the color to be solid across the word. It seems like some effect is taking over and it is not clear to me what triggers it. Sometimes if I zoom in/out it changes from Before to After image.

Any ideas? Have you noticed this before?

Thanks!

**Comment by wandersoncferreira** [comment]
Quick update on that, I dig a bit into it and seems related to extra-bold weight in the font.

**Comment by kostafey** [comment]
Hello, @wandersoncferreira. Sorry for the late response. The font rendering behavior depends on different things.

It can depend on:
- Operation system type
- Graphics driver settings
- Fonts rendering and antialiasing system configuration
- Emacs fonts and antialiasing configuration
- Specific font

It can't depend on:
- Emacs color theme ;)

So, for Windows open Start menu and type `Adjust ClearType text`.  Follow the ClearType configuration steps choosing the best font rendering cases.

For Linux, you can read the following: https://pandasauce.org/post/linux-fonts/
If you use Debian, you can try font rendering from Ubuntu: https://lovingthepenguin.blogspot.com/2010/07/ubuntu-font-rendering-in-debian-squeeze.html

Here is my personal Emacs fonts configuration for both Linux and Windows:
```elisp
 (case system-type
  ('windows-nt
   (set-face-font 'default "Consolas-14.5:antialias=subpixel"))
  ('gnu/linux
   (set-face-font 'default "FiraMonoMedium-12.0:antialias=subpixel:rgba=rgb")))
```

**Comment by wandersoncferreira** [comment]
Thanks for the links. I realized the problem was related to something else when I used my macos some weeks ago rsrs. I will close the issue from my side.
